packaging:
  input-dir: "themes"
  output-dir: "dist"
  max-versions: 10

  templates:
    readme: "src/readme-template.md"
    index-html: "src/index-template.html"

  repo:
    name: "official"
    branch: "repo"

    # Direct download urls of theme files
    # Can add multiple mirrors, will be tried in order
    # MUST INCLUDE:
    #        ${{theme}}: theme name
    #        ${{file}}:  filename (version.tar.gz)
    mirrors:
      - "https://my-tm.vercel.app/${{theme}}/${{file}}"
      - "https://mytm-repo.netlify.app/${{theme}}/${{file}}"
      - "https://github.com/mydehq/mytm/raw/refs/heads/repo/${{theme}}/${{file}}"
